import { Card, CardContent } from "@/components/ui/card"
import Image from "next/image"
import { Film, Star } from "lucide-react"

interface Movie {
  id: number
  title: string
  poster_path: string
  release_date: string
  vote_average: number
}

interface PdfCollectionTemplateProps {
  collectionName: string
  collectionDescription?: string
  lastUpdated: string
  movies: Movie[]
}

export default function PdfCollectionTemplate({
  collectionName,
  collectionDescription,
  lastUpdated,
  movies,
}: PdfCollectionTemplateProps) {
  return (
    <div className="p-8 bg-white">
      <div className="flex justify-between items-start mb-6">
        <div>
          <h1 className="text-2xl font-bold">{collectionName}</h1>
          {collectionDescription && <p className="text-gray-500 mt-1">{collectionDescription}</p>}
          <p className="text-gray-400 text-sm mt-2">Last updated: {lastUpdated}</p>
        </div>
        <div className="flex items-center text-primary">
          <Film className="h-5 w-5 mr-1" />
          <span className="font-medium">MoodyFlicks</span>
        </div>
      </div>

      <hr className="mb-6" />

      {movies.length === 0 ? (
        <div className="text-center py-8 text-gray-500">
          <p>No movies in this collection</p>
        </div>
      ) : (
        <div className="grid grid-cols-2 gap-4">
          {movies.map((movie) => (
            <Card key={movie.id} className="overflow-hidden border">
              <CardContent className="p-3">
                <div className="grid grid-cols-[80px_1fr] gap-3">
                  <div className="relative aspect-[2/3]">
                    <Image
                      src={
                        movie.poster_path
                          ? `https://image.tmdb.org/t/p/w200${movie.poster_path}`
                          : "/placeholder.svg?height=200&width=133"
                      }
                      alt={movie.title}
                      fill
                      className="object-cover rounded"
                    />
                  </div>

                  <div>
                    <h3 className="font-medium mb-1">{movie.title}</h3>
                    <div className="flex items-center text-xs text-gray-500">
                      <Star className="h-3 w-3 text-yellow-500 mr-1" />
                      <span>{movie.vote_average?.toFixed(1)}</span>
                      <span className="mx-1">•</span>
                      <span>{new Date(movie.release_date).getFullYear()}</span>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <div className="mt-8 text-center text-xs text-gray-400">
        <p>Generated by MoodyFlicks on {new Date().toLocaleDateString()}</p>
      </div>
    </div>
  )
}

